spring:
  application:
    name: spring-boot-mybatis
  datasource:
    url: jdbc:mysql://rm-bp1o892eutomay3940o.mysql.rds.aliyuncs.com/dev_db?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: mzdb
    password: MOziDB2018
    driver-class-name: com.mysql.jdbc.Driver